# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kanitkameh/Documents/Parser

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kanitkameh/Documents/Parser

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kanitkameh/Documents/Parser/CMakeFiles /home/kanitkameh/Documents/Parser/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kanitkameh/Documents/Parser/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named runTests

# Build rule for target.
runTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runTests
.PHONY : runTests

# fast build rule for target.
runTests/fast:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/build
.PHONY : runTests/fast

#=============================================================================
# Target rules for targets named ProjectName

# Build rule for target.
ProjectName: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ProjectName
.PHONY : ProjectName

# fast build rule for target.
ProjectName/fast:
	$(MAKE) -f CMakeFiles/ProjectName.dir/build.make CMakeFiles/ProjectName.dir/build
.PHONY : ProjectName/fast

src/EqualityCommand.o: src/EqualityCommand.cpp.o

.PHONY : src/EqualityCommand.o

# target to build an object file
src/EqualityCommand.cpp.o:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/src/EqualityCommand.cpp.o
	$(MAKE) -f CMakeFiles/ProjectName.dir/build.make CMakeFiles/ProjectName.dir/src/EqualityCommand.cpp.o
.PHONY : src/EqualityCommand.cpp.o

src/EqualityCommand.i: src/EqualityCommand.cpp.i

.PHONY : src/EqualityCommand.i

# target to preprocess a source file
src/EqualityCommand.cpp.i:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/src/EqualityCommand.cpp.i
	$(MAKE) -f CMakeFiles/ProjectName.dir/build.make CMakeFiles/ProjectName.dir/src/EqualityCommand.cpp.i
.PHONY : src/EqualityCommand.cpp.i

src/EqualityCommand.s: src/EqualityCommand.cpp.s

.PHONY : src/EqualityCommand.s

# target to generate assembly for a file
src/EqualityCommand.cpp.s:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/src/EqualityCommand.cpp.s
	$(MAKE) -f CMakeFiles/ProjectName.dir/build.make CMakeFiles/ProjectName.dir/src/EqualityCommand.cpp.s
.PHONY : src/EqualityCommand.cpp.s

src/IfCommand.o: src/IfCommand.cpp.o

.PHONY : src/IfCommand.o

# target to build an object file
src/IfCommand.cpp.o:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/src/IfCommand.cpp.o
	$(MAKE) -f CMakeFiles/ProjectName.dir/build.make CMakeFiles/ProjectName.dir/src/IfCommand.cpp.o
.PHONY : src/IfCommand.cpp.o

src/IfCommand.i: src/IfCommand.cpp.i

.PHONY : src/IfCommand.i

# target to preprocess a source file
src/IfCommand.cpp.i:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/src/IfCommand.cpp.i
	$(MAKE) -f CMakeFiles/ProjectName.dir/build.make CMakeFiles/ProjectName.dir/src/IfCommand.cpp.i
.PHONY : src/IfCommand.cpp.i

src/IfCommand.s: src/IfCommand.cpp.s

.PHONY : src/IfCommand.s

# target to generate assembly for a file
src/IfCommand.cpp.s:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/src/IfCommand.cpp.s
	$(MAKE) -f CMakeFiles/ProjectName.dir/build.make CMakeFiles/ProjectName.dir/src/IfCommand.cpp.s
.PHONY : src/IfCommand.cpp.s

src/PlusCommand.o: src/PlusCommand.cpp.o

.PHONY : src/PlusCommand.o

# target to build an object file
src/PlusCommand.cpp.o:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/src/PlusCommand.cpp.o
	$(MAKE) -f CMakeFiles/ProjectName.dir/build.make CMakeFiles/ProjectName.dir/src/PlusCommand.cpp.o
.PHONY : src/PlusCommand.cpp.o

src/PlusCommand.i: src/PlusCommand.cpp.i

.PHONY : src/PlusCommand.i

# target to preprocess a source file
src/PlusCommand.cpp.i:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/src/PlusCommand.cpp.i
	$(MAKE) -f CMakeFiles/ProjectName.dir/build.make CMakeFiles/ProjectName.dir/src/PlusCommand.cpp.i
.PHONY : src/PlusCommand.cpp.i

src/PlusCommand.s: src/PlusCommand.cpp.s

.PHONY : src/PlusCommand.s

# target to generate assembly for a file
src/PlusCommand.cpp.s:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/src/PlusCommand.cpp.s
	$(MAKE) -f CMakeFiles/ProjectName.dir/build.make CMakeFiles/ProjectName.dir/src/PlusCommand.cpp.s
.PHONY : src/PlusCommand.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectName.dir/build.make CMakeFiles/ProjectName.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectName.dir/build.make CMakeFiles/ProjectName.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectName.dir/build.make CMakeFiles/ProjectName.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/src/utils.cpp.o
	$(MAKE) -f CMakeFiles/ProjectName.dir/build.make CMakeFiles/ProjectName.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/src/utils.cpp.i
	$(MAKE) -f CMakeFiles/ProjectName.dir/build.make CMakeFiles/ProjectName.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/src/utils.cpp.s
	$(MAKE) -f CMakeFiles/ProjectName.dir/build.make CMakeFiles/ProjectName.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

tests/EqualityCommandTest.o: tests/EqualityCommandTest.cpp.o

.PHONY : tests/EqualityCommandTest.o

# target to build an object file
tests/EqualityCommandTest.cpp.o:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/tests/EqualityCommandTest.cpp.o
.PHONY : tests/EqualityCommandTest.cpp.o

tests/EqualityCommandTest.i: tests/EqualityCommandTest.cpp.i

.PHONY : tests/EqualityCommandTest.i

# target to preprocess a source file
tests/EqualityCommandTest.cpp.i:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/tests/EqualityCommandTest.cpp.i
.PHONY : tests/EqualityCommandTest.cpp.i

tests/EqualityCommandTest.s: tests/EqualityCommandTest.cpp.s

.PHONY : tests/EqualityCommandTest.s

# target to generate assembly for a file
tests/EqualityCommandTest.cpp.s:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/tests/EqualityCommandTest.cpp.s
.PHONY : tests/EqualityCommandTest.cpp.s

tests/PlusCommandTest.o: tests/PlusCommandTest.cpp.o

.PHONY : tests/PlusCommandTest.o

# target to build an object file
tests/PlusCommandTest.cpp.o:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/tests/PlusCommandTest.cpp.o
.PHONY : tests/PlusCommandTest.cpp.o

tests/PlusCommandTest.i: tests/PlusCommandTest.cpp.i

.PHONY : tests/PlusCommandTest.i

# target to preprocess a source file
tests/PlusCommandTest.cpp.i:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/tests/PlusCommandTest.cpp.i
.PHONY : tests/PlusCommandTest.cpp.i

tests/PlusCommandTest.s: tests/PlusCommandTest.cpp.s

.PHONY : tests/PlusCommandTest.s

# target to generate assembly for a file
tests/PlusCommandTest.cpp.s:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/tests/PlusCommandTest.cpp.s
.PHONY : tests/PlusCommandTest.cpp.s

tests/main.o: tests/main.cpp.o

.PHONY : tests/main.o

# target to build an object file
tests/main.cpp.o:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/tests/main.cpp.o
.PHONY : tests/main.cpp.o

tests/main.i: tests/main.cpp.i

.PHONY : tests/main.i

# target to preprocess a source file
tests/main.cpp.i:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/tests/main.cpp.i
.PHONY : tests/main.cpp.i

tests/main.s: tests/main.cpp.s

.PHONY : tests/main.s

# target to generate assembly for a file
tests/main.cpp.s:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/tests/main.cpp.s
.PHONY : tests/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... runTests"
	@echo "... ProjectName"
	@echo "... src/EqualityCommand.o"
	@echo "... src/EqualityCommand.i"
	@echo "... src/EqualityCommand.s"
	@echo "... src/IfCommand.o"
	@echo "... src/IfCommand.i"
	@echo "... src/IfCommand.s"
	@echo "... src/PlusCommand.o"
	@echo "... src/PlusCommand.i"
	@echo "... src/PlusCommand.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... tests/EqualityCommandTest.o"
	@echo "... tests/EqualityCommandTest.i"
	@echo "... tests/EqualityCommandTest.s"
	@echo "... tests/PlusCommandTest.o"
	@echo "... tests/PlusCommandTest.i"
	@echo "... tests/PlusCommandTest.s"
	@echo "... tests/main.o"
	@echo "... tests/main.i"
	@echo "... tests/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

